const SESSION_KEYS = [
    'dateTime',
    'recorder',
    'handler',
    'site',
    'array',
    'noCaptures',
    'trapStatus',
    'commentsAboutTheArray',
];

const TURTLE_KEYS = [
    'dateTime',
    'site',
    'array',
    'fenceTrap',
    'taxa',
    'speciesCode',
    'genus',
    'species',
    'massG',
    'sex',
    'dead',
    'comments',
];

const LIZARD_KEYS = [
    'dateTime',
    'site',
    'array',
    'fenceTrap',
    'taxa',
    'speciesCode',
    'genus',
    'species',
    'toeClipCode',
    'recapture',
    'svlMm',
    'vtlMm',
    'regenTail',
    'otlMm',
    'hatchling',
    'massG',
    'sex',
    'dead',
    'comments',
];

const MAMMAL_KEYS = [
    'dateTime',
    'site',
    'array',
    'fenceTrap',
    'taxa',
    'speciesCode',
    'genus',
    'species',
    'massG',
    'sex',
    'dead',
    'comments',
];

const SNAKE_KEYS = [
    'dateTime',
    'site',
    'array',
    'fenceTrap',
    'taxa',
    'speciesCode',
    'genus',
    'species',
    'svlMm',
    'vtlMm',
    'massG',
    'sex',
    'dead',
    'comments',
];

const ARTHROPOD_KEYS = [
    'dateTime',
    'site',
    'array',
    'fenceTrap',
    'predator',
    'aran',
    'auch',
    'blat',
    'chil',
    'cole',
    'crus',
    'derm',
    'diel',
    'dipt',
    'hete',
    'hyma',
    'hymb',
    'lepi',
    'mant',
    'orth',
    'pseu',
    'scor',
    'soli',
    'thys',
    'unki',
    'micro',
    'comments',
];

const AMPHIBIAN_KEYS = [
    'dateTime',
    'site',
    'array',
    'fenceTrap',
    'taxa',
    'speciesCode',
    'genus',
    'species',
    'hdBody',
    'massG',
    'sex',
    'dead',
    'comments',
];

export const TABLE_KEYS = {
    'Session': SESSION_KEYS,
    'Turtle': TURTLE_KEYS,
    'Lizard': LIZARD_KEYS,
    'Mammal': MAMMAL_KEYS,
    'Snake': SNAKE_KEYS,
    'Arthropod': ARTHROPOD_KEYS,
    'Amphibian': AMPHIBIAN_KEYS
}