export const labelKeyMap = {
    'Date & Time': 'dateTime',
    'Recorder': 'recorder',
    'Handler': 'handler',
    'Site': 'site',
    'Array': 'array',
    'No Captures': 'noCaptures',
    'Trap Status': 'trapStatus',
    'Comments': 'commentsAboutTheArray',
    'Fence Trap': 'fenceTrap',
    'Taxa': 'taxa',
    'Species Code': 'speciesCode',
    'Genus': 'genus',
    'Species': 'species',
    'Mass(g)': 'massG',
    'Dead?': 'dead',
    'Toe-clip Code': 'toeClipCode',
    'Recapture': 'recapture',
    'SVL(mm)': 'svlMm',
    'VTL(mm)': 'vtlMm',
    'Regen Tail?': 'regenTail',
    'OTL(mm)': 'otlMm',
    'Hatchling?': 'hatchling',
    'Predator?': 'predator',
    'ARAN': 'aran',
    'AUCH': 'auch',
    'BLAT': 'blat',
    'CHIL': 'chil',
    'COLE': 'cole',
    'CRUS': 'crus',
    'DERM': 'derm',
    'DIEL': 'diel',
    'DIPT': 'dipt',
    'HETE': 'hete',
    'HYMA': 'hyma',
    'HYMB': 'hymb',
    'LEPI': 'lepi',
    'MANT': 'mant',
    'ORTH': 'orth',
    'PSEU': 'pseu',
    'SCOR': 'scor',
    'SOLI': 'soli',
    'THYS': 'thys',
    'UNKI': 'unki',
    'MICRO': 'micro',
}

// Reverse the relationship in the above map manually
export const keyLabelMap = {
    dateTime: 'Date & Time',
    recorder: 'Recorder',
    handler: 'Handler',
    site: 'Site',
    array: 'Array',
    noCaptures: 'No Captures',
    trapStatus: 'Trap Status',
    commentsAboutTheArray: 'Comments',
    fenceTrap: 'Fence Trap',
    taxa: 'Taxa',
    speciesCode: 'Species Code',
    genus: 'Genus',
    species: 'Species',
    massG: 'Mass(g)',
    dead: 'Dead?',
    toeClipCode: 'Toe-clip Code',
    recapture: 'Recapture',
    svlMm: 'SVL(mm)',
    vtlMm: 'VTL(mm)',
    regenTail: 'Regen Tail?',
    otlMm: 'OTL(mm)',
    hatchling: 'Hatchling?',
    predator: 'Predator?',
    aran: 'ARAN',
    auch: 'AUCH',
    blat: 'BLAT',
    chil: 'CHIL',
    cole: 'COLE',
    crus: 'CRUS',
    derm: 'DERM',
    diel: 'DIEL',
    dipt: 'DIPT',
    hete: 'HETE',
    hyma: 'HYMA',
    hymb: 'HYMB',
    lepi: 'LEPI',
    mant: 'MANT',
    orth: 'ORTH',
    pseu: 'PSEU',
    scor: 'SCOR',
    soli: 'SOLI',
    thys: 'THYS',
    unki: 'UNKI',
    micro: 'MICRO',
}


const sessionLabels = [
    'Date & Time',
    'Recorder',
    'Handler',
    'Site',
    'Array',
    'No Captures',
    'Trap Status',
    'Comments',
];

const turtleLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const lizardLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'Toe-clip Code',
    'Recapture',
    'SVL(mm)',
    'VTL(mm)',
    'Regen Tail?',
    'OTL(mm)',
    'Hatchling?',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const mammalLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const snakeLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'SVL(mm)',
    'VTM(mm)',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const arthropodLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Predator?',
    'ARAN',
    'AUCH',
    'BLAT',
    'CHIL',
    'COLE',
    'CRUS',
    'DERM',
    'DIEL',
    'DIPT',
    'HETE',
    'HYMA',
    'HYMB',
    'LEPI',
    'MANT',
    'ORTH',
    'PSEU',
    'SCOR',
    'SOLI',
    'THYS',
    'UNKI',
    'MICRO',
    'Comments',
];

const amphibianLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'HD-Body',
    'Mass(g)',
    'Sex',
    'Dead',
    'Comments',
];

export const TABLE_LABELS = {
    Session: sessionLabels,
    Turtle: turtleLabels,
    Lizard: lizardLabels,
    Mammal: mammalLabels,
    Snake: snakeLabels,
    Arthropod: arthropodLabels,
    Amphibian: amphibianLabels,
};
