const sessionLabels = [
    'Date & Time',
    'Recorder',
    'Handler',
    'Site',
    'Array',
    'No Captures',
    'Trap Status',
    'Comments',
];

const turtleLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const lizardLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'Toe-clip Code',
    'Recapture',
    'SVL(mm)',
    'VTL(mm)',
    'Regen Tail?',
    'OTL(mm)',
    'Hatchling?',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const mammalLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const snakeLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'SVL(mm)',
    'VTM(mm)',
    'Mass(g)',
    'Sex',
    'Dead?',
    'Comments',
];

const arthropodLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Predator?',
    'ARAN',
    'AUCH',
    'BLAT',
    'CHIL',
    'COLE',
    'CRUS',
    'DERM',
    'DIEL',
    'DIPT',
    'HETE',
    'HYMA',
    'HYMB',
    'LEPI',
    'MANT',
    'ORTH',
    'PSEU',
    'SCOR',
    'SOLI',
    'THYS',
    'UNKI',
    'MICRO',
    'Comments',
];

const amphibianLabels = [
    'Date & Time',
    'Site',
    'Array',
    'Fence Trap',
    'Taxa',
    'Species Code',
    'Genus',
    'Species',
    'HD-Body',
    'Mass(g)',
    'Sex',
    'Dead',
    'Comments',
];

export const TABLE_LABELS = {
    Session: sessionLabels,
    Turtle: turtleLabels,
    Lizard: lizardLabels,
    Mammal: mammalLabels,
    Snake: snakeLabels,
    Arthropod: arthropodLabels,
    Amphibian: amphibianLabels,
};
