name: AutoPretty

on:
  push:
    branches:
      - "main"
      - "dev"
      - "US**"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "US**"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{html,css,js,md} --config .prettierrc
          only_changed: False